# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(703, 317)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 431, 291))
        self.groupBox.setObjectName("groupBox")
        self.lName = QtWidgets.QLabel(self.groupBox)
        self.lName.setGeometry(QtCore.QRect(20, 30, 401, 16))
        self.lName.setObjectName("lName")
        self.lCountTraining = QtWidgets.QLabel(self.groupBox)
        self.lCountTraining.setGeometry(QtCore.QRect(20, 50, 401, 16))
        self.lCountTraining.setObjectName("lCountTraining")
        self.lValueTraining = QtWidgets.QLabel(self.groupBox)
        self.lValueTraining.setGeometry(QtCore.QRect(20, 70, 401, 16))
        self.lValueTraining.setObjectName("lValueTraining")
        self.lCountInputNeuron = QtWidgets.QLabel(self.groupBox)
        self.lCountInputNeuron.setGeometry(QtCore.QRect(20, 90, 401, 16))
        self.lCountInputNeuron.setObjectName("lCountInputNeuron")
        self.lCountOutputNeuron = QtWidgets.QLabel(self.groupBox)
        self.lCountOutputNeuron.setGeometry(QtCore.QRect(20, 110, 401, 16))
        self.lCountOutputNeuron.setObjectName("lCountOutputNeuron")
        self.lCountHiddenNeuron = QtWidgets.QLabel(self.groupBox)
        self.lCountHiddenNeuron.setGeometry(QtCore.QRect(20, 130, 401, 16))
        self.lCountHiddenNeuron.setObjectName("lCountHiddenNeuron")
        self.lCountHiddenNeural = QtWidgets.QLabel(self.groupBox)
        self.lCountHiddenNeural.setGeometry(QtCore.QRect(20, 150, 401, 16))
        self.lCountHiddenNeural.setObjectName("lCountHiddenNeural")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 210, 401, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.bSaveNeural = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.bSaveNeural.setObjectName("bSaveNeural")
        self.gridLayout.addWidget(self.bSaveNeural, 1, 0, 1, 1)
        self.bSaveAsNeural = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.bSaveAsNeural.setObjectName("bSaveAsNeural")
        self.gridLayout.addWidget(self.bSaveAsNeural, 1, 1, 1, 1)
        self.bTestNeural = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.bTestNeural.setObjectName("bTestNeural")
        self.gridLayout.addWidget(self.bTestNeural, 0, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(449, 9, 241, 291))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 221, 111))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bOpenNeural = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.bOpenNeural.setObjectName("bOpenNeural")
        self.gridLayout_2.addWidget(self.bOpenNeural, 1, 0, 1, 1)
        self.bCreateNewNeural = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.bCreateNewNeural.setObjectName("bCreateNewNeural")
        self.gridLayout_2.addWidget(self.bCreateNewNeural, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Neural"))
        self.groupBox.setTitle(_translate("MainWindow", "Текущая нейроная сеть"))
        self.lName.setText(_translate("MainWindow", "Название:"))
        self.lCountTraining.setText(_translate("MainWindow", "Количество примеров обучения сети:"))
        self.lValueTraining.setText(_translate("MainWindow", "Коэффицент обучения:"))
        self.lCountInputNeuron.setText(_translate("MainWindow", "Количество нейронов входного слоя"))
        self.lCountOutputNeuron.setText(_translate("MainWindow", "Количество нейронов выходного слоя"))
        self.lCountHiddenNeuron.setText(_translate("MainWindow", "Количество нейронов промежуточного слоя"))
        self.lCountHiddenNeural.setText(_translate("MainWindow", "Количество промежуточных слоев"))
        self.bSaveNeural.setText(_translate("MainWindow", "Сохранить"))
        self.bSaveAsNeural.setText(_translate("MainWindow", "Сохранить как"))
        self.bTestNeural.setText(_translate("MainWindow", "Обучение и тестирование"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Изменить текущую нейроную сеть"))
        self.bOpenNeural.setText(_translate("MainWindow", "Открыть существующую"))
        self.bCreateNewNeural.setText(_translate("MainWindow", "Создать новую"))

