# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TestDialog(object):
    def setupUi(self, TestDialog):
        TestDialog.setObjectName("TestDialog")
        TestDialog.resize(893, 651)
        self.groupBox = QtWidgets.QGroupBox(TestDialog)
        self.groupBox.setGeometry(QtCore.QRect(440, 540, 441, 101))
        self.groupBox.setObjectName("groupBox")
        self.bOpenFileTrain = QtWidgets.QPushButton(self.groupBox)
        self.bOpenFileTrain.setGeometry(QtCore.QRect(10, 20, 321, 41))
        self.bOpenFileTrain.setObjectName("bOpenFileTrain")
        self.lStatusTrain = QtWidgets.QLabel(self.groupBox)
        self.lStatusTrain.setGeometry(QtCore.QRect(10, 70, 321, 21))
        self.lStatusTrain.setText("")
        self.lStatusTrain.setAlignment(QtCore.Qt.AlignCenter)
        self.lStatusTrain.setObjectName("lStatusTrain")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setGeometry(QtCore.QRect(340, 60, 91, 31))
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(100)
        self.spinBox.setObjectName("spinBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(340, 30, 91, 21))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(TestDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 421, 551))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lResult = QtWidgets.QLabel(self.groupBox_2)
        self.lResult.setGeometry(QtCore.QRect(10, 480, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.lResult.setFont(font)
        self.lResult.setText("")
        self.lResult.setAlignment(QtCore.Qt.AlignCenter)
        self.lResult.setObjectName("lResult")
        self.bGetChar = QtWidgets.QPushButton(self.groupBox_2)
        self.bGetChar.setGeometry(QtCore.QRect(10, 440, 121, 28))
        self.bGetChar.setObjectName("bGetChar")
        self.bClear = QtWidgets.QPushButton(self.groupBox_2)
        self.bClear.setGeometry(QtCore.QRect(320, 440, 93, 28))
        self.bClear.setObjectName("bClear")
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(10, 30, 400, 400))
        self.widget.setObjectName("widget")
        self.lineEditRes = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditRes.setGeometry(QtCore.QRect(170, 510, 111, 22))
        self.lineEditRes.setMaxLength(1)
        self.lineEditRes.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditRes.setObjectName("lineEditRes")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(130, 480, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.groupBox_3 = QtWidgets.QGroupBox(TestDialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 211, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lName1 = QtWidgets.QLabel(self.groupBox_3)
        self.lName1.setGeometry(QtCore.QRect(20, 20, 181, 16))
        self.lName1.setObjectName("lName1")
        self.groupBox_4 = QtWidgets.QGroupBox(TestDialog)
        self.groupBox_4.setGeometry(QtCore.QRect(440, 10, 441, 271))
        self.groupBox_4.setObjectName("groupBox_4")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox.setGeometry(QtCore.QRect(270, 20, 161, 20))
        self.checkBox.setObjectName("checkBox")
        self.bOpenFileTest = QtWidgets.QPushButton(self.groupBox_4)
        self.bOpenFileTest.setGeometry(QtCore.QRect(20, 30, 181, 41))
        self.bOpenFileTest.setObjectName("bOpenFileTest")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setGeometry(QtCore.QRect(220, 70, 211, 91))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_4.setObjectName("label_4")
        self.lTrue1 = QtWidgets.QLabel(self.groupBox_5)
        self.lTrue1.setGeometry(QtCore.QRect(20, 40, 181, 16))
        self.lTrue1.setObjectName("lTrue1")
        self.lFalse1 = QtWidgets.QLabel(self.groupBox_5)
        self.lFalse1.setGeometry(QtCore.QRect(20, 60, 181, 16))
        self.lFalse1.setObjectName("lFalse1")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_6.setGeometry(QtCore.QRect(220, 160, 211, 91))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_6)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_7.setObjectName("label_7")
        self.lTrue2 = QtWidgets.QLabel(self.groupBox_6)
        self.lTrue2.setGeometry(QtCore.QRect(20, 40, 181, 16))
        self.lTrue2.setObjectName("lTrue2")
        self.lFalse2 = QtWidgets.QLabel(self.groupBox_6)
        self.lFalse2.setGeometry(QtCore.QRect(20, 60, 181, 16))
        self.lFalse2.setObjectName("lFalse2")
        self.bTest1 = QtWidgets.QPushButton(self.groupBox_4)
        self.bTest1.setGeometry(QtCore.QRect(20, 160, 181, 41))
        self.bTest1.setObjectName("bTest1")
        self.lCountExamples = QtWidgets.QLabel(self.groupBox_4)
        self.lCountExamples.setGeometry(QtCore.QRect(20, 80, 181, 16))
        self.lCountExamples.setObjectName("lCountExamples")
        self.bTest2 = QtWidgets.QPushButton(self.groupBox_4)
        self.bTest2.setGeometry(QtCore.QRect(20, 210, 181, 41))
        self.bTest2.setObjectName("bTest2")
        self.lStatusTest = QtWidgets.QLabel(self.groupBox_4)
        self.lStatusTest.setGeometry(QtCore.QRect(20, 140, 181, 16))
        self.lStatusTest.setText("")
        self.lStatusTest.setAlignment(QtCore.Qt.AlignCenter)
        self.lStatusTest.setObjectName("lStatusTest")
        self.groupBox_7 = QtWidgets.QGroupBox(TestDialog)
        self.groupBox_7.setGeometry(QtCore.QRect(220, 10, 211, 80))
        self.groupBox_7.setObjectName("groupBox_7")
        self.lName2 = QtWidgets.QLabel(self.groupBox_7)
        self.lName2.setGeometry(QtCore.QRect(20, 20, 181, 16))
        self.lName2.setObjectName("lName2")
        self.bOpen2 = QtWidgets.QPushButton(self.groupBox_7)
        self.bOpen2.setGeometry(QtCore.QRect(20, 40, 181, 31))
        self.bOpen2.setObjectName("bOpen2")

        self.retranslateUi(TestDialog)
        QtCore.QMetaObject.connectSlotsByName(TestDialog)

    def retranslateUi(self, TestDialog):
        _translate = QtCore.QCoreApplication.translate
        TestDialog.setWindowTitle(_translate("TestDialog", "Dialog"))
        self.groupBox.setTitle(_translate("TestDialog", "Обучение"))
        self.bOpenFileTrain.setText(_translate("TestDialog", "Обучить из файла"))
        self.label.setText(_translate("TestDialog", "Повторять"))
        self.groupBox_2.setTitle(_translate("TestDialog", "Тестирование 1"))
        self.bGetChar.setText(_translate("TestDialog", "Получть ответ"))
        self.bClear.setText(_translate("TestDialog", "Очистить"))
        self.label_2.setText(_translate("TestDialog", "Ожидаемый результат"))
        self.groupBox_3.setTitle(_translate("TestDialog", "Нейросеть 1"))
        self.lName1.setText(_translate("TestDialog", "Название: "))
        self.groupBox_4.setTitle(_translate("TestDialog", "Тестирование 2"))
        self.checkBox.setText(_translate("TestDialog", "Обучать если не верно"))
        self.bOpenFileTest.setText(_translate("TestDialog", "Выбрать файл тестирования"))
        self.groupBox_5.setTitle(_translate("TestDialog", "Нейросеть 1"))
        self.label_4.setText(_translate("TestDialog", "Результат:"))
        self.lTrue1.setText(_translate("TestDialog", "Верно - "))
        self.lFalse1.setText(_translate("TestDialog", "Неверно - "))
        self.groupBox_6.setTitle(_translate("TestDialog", "Нейросеть 2"))
        self.label_7.setText(_translate("TestDialog", "Результат:"))
        self.lTrue2.setText(_translate("TestDialog", "Верно - "))
        self.lFalse2.setText(_translate("TestDialog", "Неверно - "))
        self.bTest1.setText(_translate("TestDialog", "Тестировать сеть 1"))
        self.lCountExamples.setText(_translate("TestDialog", "Количество примеров - 0"))
        self.bTest2.setText(_translate("TestDialog", "Тестировать сеть 2"))
        self.groupBox_7.setTitle(_translate("TestDialog", "Нейросеть 2"))
        self.lName2.setText(_translate("TestDialog", "Название: "))
        self.bOpen2.setText(_translate("TestDialog", "Открыть"))

